import dotenv from "dotenv";

dotenv.config();

const {
  DISCORD_APPLICATION_ID,
  DISCORD_PUBLIC_KEY,
  DISCORD_TOKEN,
  DISCORD_GUILD_ID,
  SUPABASE_PROJECT_URL,
  SUPABASE_PUBLIC_KEY,
  SUPABASE_USER,
  SUPABASE_PASSWORD,
  LLM_BASE_URL,
  LLM_API_KEY,
} = process.env;

if (
  !DISCORD_APPLICATION_ID ||
  !DISCORD_PUBLIC_KEY ||
  !DISCORD_TOKEN ||
  !SUPABASE_PROJECT_URL ||
  !SUPABASE_PUBLIC_KEY ||
  !SUPABASE_USER ||
  !SUPABASE_PASSWORD ||
  !LLM_BASE_URL ||
  !LLM_API_KEY
) {
  throw new Error("Missing environment variables");
}

export const config = {
  DISCORD_APPLICATION_ID,
  DISCORD_PUBLIC_KEY,
  DISCORD_TOKEN,
  DISCORD_GUILD_ID,
  SUPABASE_PROJECT_URL,
  SUPABASE_PUBLIC_KEY,
  SUPABASE_USER,
  SUPABASE_PASSWORD,
  LLM_BASE_URL,
  LLM_API_KEY,
};
