name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - run: echo "${{ secrets.PROD_ENV_VARS }}" >> ./.env
      - run: npm install
      - run: pm2 restart ecosystem.config.js
